# Generated by Django 4.0.5 on 2022-08-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='user_name',
            new_name='user',
        ),
    ]
