# Generated by Django 4.0.5 on 2022-08-18 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_delete_post_rename_user_name_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateField(default=datetime.date(2022, 8, 18)),
        ),
    ]
